### ISSUE TITLE
Karma 6.0.0 gives error Unknown arguments: skip-tags, skipTags

### ISSUE THREAD

**Issue by rajsite** [mnasyrov/karma-jasmine-spec-tags#12]
Karma 6.0.0 introduced a [breaking change](https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#breaking-changes) where the cli errors on "unexpected options or parameters". This results in the following error in the console with karma-jasmine-spec-tags:
```
Unknown arguments: skip-tags, skipTags
```

**Comment by mnasyrov** [comment]
As I see, custom CLI arguments cannot be used with Karma anymore. Please try to configure the plugin by Karma's configuration file: https://github.com/mnasyrov/karma-jasmine-spec-tags#configuration

**Comment by mnasyrov** [comment]
Karma removed strict parsing of custom arguments in 6.0.4, it fixed the issue. I updated the peer dependencies.

Fixed in karma-jasmine-spec-tags@2.0.0
